#! /bin/bash

cd src/tex/
./makeSlides
./makeAssign

## PDF nach /slide verschieben
mv ps2012gesis-ma-workshop.pdf ../../slide/

## Oeffentlichen Ordner erstellen und Daten kopieren
if [ -d "../../../ps2012gesis-ma-workshop_pub" ]; 
then
    rm -rfv ../../../ps2012gesis-ma-workshop_pub
	mkdir ../../../ps2012gesis-ma-workshop_pub
else
	mkdir ../../../ps2012gesis-ma-workshop_pub
fi

cp -r ../../. ../../../ps2012gesis-ma-workshop_pub

## Sensitive Daten im oeffentlichen Ordner loeschen
rm -rfv ../../../ps2012gesis-ma-workshop_pub/src/tex/logo.pdf
rm -rfv ../../../ps2012gesis-ma-workshop_pub/src/tex/logo-small.pdf
rm -rfv ../../../ps2012gesis-ma-workshop_pub/ref/nopubdoc
rm -rfv ../../../ps2012gesis-ma-workshop_pub/org/nopubdoc
rm -rfv ../../../ps2012gesis-ma-workshop_pub/.git
