#+TITLE: Materialien zum GESIS Workshop "Grundlagen sozialwissenschaftlicher Meta-Analysen" 
#+AUTHOR: Bernd Weiß
#+DATE: 13./14. Dezember 2012


* Übersicht
  Am 13. und 14. Dezember wurde bei der GESIS - Leibniz-Institut für Sozialwissenschaften in Köln ein Workshop über die
  "[[http://www.gesis.org/veranstaltungen/gesis-workshops/metaanalysen/][Grundlagen sozialwissenschaftlicher Meta-Analysen]]" abgehalten. Auf dieser
  Website finden sich (fast) alle Kursmaterialien. Alle Materialien (soweit
  sie nicht die Rechte anderer betreffen) stehen unter einer [[http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en][Creative Commons
  Attribution-NonCommercial-ShareAlike 3.0 Germany Lizenz]].

  Der Kurs wurde in dieser Version zum ersten Mal durchgeführt und ist an einigen
  Stellen sicherlich noch verbesserungswürdig. Über entsprechende Rückmeldungen
  würde ich mich freuen. 

* Inhalt
  Die Kursfolien sind im Verzeichnis =slide/= enthalten, die Übungsblätter
  im Verzeichnis =assign=. Der R-, Stata- und LaTeX-Code ist im Verzeichnis
  =src/= zu finden.

  Um die Folien (siehe =/slide=) bzw. die Übungsblätter (siehe =/assign=)
  erneut zu erstellen, können die Skripte =makeSlides= und =makeAssign= in =/src/tex= genutzt
  werden. Dafür wird die folgende Software benötigt: LaTeX, R, biber,
  bash. 

* Download
  Der Download sämtlicher Materialien ist auf zweierlei Wegen möglich: 
  - =git clone ...=
  - Als zip-Archiv (siehe ZIP Button oberhalb der Datei-/Verzeichnisliste)

* Datensätze
  Im Verzeichnis =data/= sind zwei Datensätze enthalten:

  - =dBCG.csv= (Quelle: Colditz GA, B. T. (1994). Efficacy of bcg vaccine in the
    prevention of tuberculosis: Meta-analysis of the published literature. JAMA:
    The Journal of the American Medical Association, 271(9),
    698–702. doi:10.1001/jama.1994.03510330076038; basiert auf dem Datensatz im
    R Paket =metafor=)
  - =dVerbAb.csv= (Quelle: Aloe, A. M., & Becker, B. J. (2009). Teacher Verbal
    Ability and School Outcomes. Educational Researcher, 38(8), 612
    –624. doi:10.3102/0013189X09353939)
